**Import Modules**

In [1]:
import pandas as pd

**import and read CSV**

In [2]:
### Read Mental Health Datset usingpandas function called read_csv
df = pd.read_csv('./capstone/Mental Health Dataset.csv')

In [3]:
###Checking column names of the dataset using df.columns
df.columns

Index(['Timestamp', 'Gender', 'Country', 'Occupation', 'self_employed',
       'family_history', 'treatment', 'Days_Indoors', 'Growing_Stress',
       'Changes_Habits', 'Mental_Health_History', 'Mood_Swings',
       'Coping_Struggles', 'Work_Interest', 'Social_Weakness',
       'mental_health_interview', 'care_options'],
      dtype='object')

In [4]:
###Getting the information of first five rows using pandas function called df.head
df.head(5)

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [5]:
###Getting to know the datatypes of the columns using df.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292364 entries, 0 to 292363
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Timestamp                292364 non-null  object
 1   Gender                   292364 non-null  object
 2   Country                  292364 non-null  object
 3   Occupation               292364 non-null  object
 4   self_employed            287162 non-null  object
 5   family_history           292364 non-null  object
 6   treatment                292364 non-null  object
 7   Days_Indoors             292364 non-null  object
 8   Growing_Stress           292364 non-null  object
 9   Changes_Habits           292364 non-null  object
 10  Mental_Health_History    292364 non-null  object
 11  Mood_Swings              292364 non-null  object
 12  Coping_Struggles         292364 non-null  object
 13  Work_Interest            292364 non-null  object
 14  Social_Weakness          292364 non-null  object
 15  mental_health_interview  292364 non-null  object
 16  care_options             292364 non-null  object
dtypes: object(17)
memory usage: 37.9+ MB

**Split TimeStamp Column into two seperate columns**

In [6]:
### Makinh a copy of the original dataframe before making any changes in it
df_copy = df.copy()

In [9]:
### Convert 'Timestamp' column to datetime
df_copy['Timestamp'] = pd.to_datetime(df_copy['Timestamp'])

### Extract date and time into new columns
df_copy['Date'] = df_copy['Timestamp'].dt.date
df_copy['Time'] = df_copy['Timestamp'].dt.time

### Droping the original 'Timestamp' column
df_copy = df_copy.drop(columns=['Timestamp'])

print("\nDataFrame with Date and Time columns:")
print(df_copy)

DataFrame with Date and Time columns:
        Gender        Country Occupation self_employed family_history  \
0       Female  United States  Corporate           NaN             No
1       Female  United States  Corporate           NaN            Yes
2       Female  United States  Corporate           NaN            Yes
3       Female  United States  Corporate            No            Yes
4       Female  United States  Corporate            No            Yes
...        ...            ...        ...           ...            ...
292359    Male  United States   Business           Yes            Yes
292360    Male   South Africa   Business            No            Yes
292361    Male  United States   Business            No            Yes
292362    Male  United States   Business            No            Yes
292363    Male  United States   Business            No            Yes

       treatment Days_Indoors Growing_Stress Changes_Habits  \
0            Yes    1-14 days            Yes             No
1            Yes    1-14 days            Yes             No
2            Yes    1-14 days            Yes             No
3            Yes    1-14 days            Yes             No
4            Yes    1-14 days            Yes             No
...          ...          ...            ...            ...
292359       Yes   15-30 days             No          Maybe
292360       Yes   15-30 days             No          Maybe
292361        No   15-30 days             No          Maybe
292362       Yes   15-30 days             No          Maybe
292363       Yes   15-30 days             No          Maybe

       Mental_Health_History Mood_Swings Coping_Struggles Work_Interest  \
0                        Yes      Medium               No            No
1                        Yes      Medium               No            No
2                        Yes      Medium               No            No
3                        Yes      Medium               No            No
4                        Yes      Medium               No            No
...                      ...         ...              ...           ...
292359                    No         Low              Yes            No
292360                    No         Low              Yes            No
292361                    No         Low              Yes            No
292362                    No         Low              Yes            No
292363                    No         Low              Yes            No

       Social_Weakness mental_health_interview care_options        Date  \
0                  Yes                      No     Not sure  2014-08-27
1                  Yes                      No           No  2014-08-27
2                  Yes                      No          Yes  2014-08-27
3                  Yes                   Maybe          Yes  2014-08-27
4                  Yes                      No          Yes  2014-08-27
...                ...                     ...          ...         ...
292359           Maybe                   Maybe     Not sure  2015-07-27
292360           Maybe                      No          Yes  2015-08-17
292361           Maybe                      No           No  2015-08-25
292362           Maybe                      No          Yes  2015-09-26
292363           Maybe                      No          Yes  2016-02-01

            Time
0       11:29:00
1       11:31:00
2       11:32:00
3       11:37:00
4       11:43:00
...          ...
292359  23:25:00
292360  09:38:00
292361  19:59:00
292362  01:07:00
292363  23:04:00

[292364 rows x 18 columns]

In [10]:
df_copy

,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options,Date,Time
0,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure,2014-08-27,11:29:00
1,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No,2014-08-27,11:31:00
2,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes,2014-08-27,11:32:00
3,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes,2014-08-27,11:37:00
4,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes,2014-08-27,11:43:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292359,Male,United States,Business,Yes,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,Maybe,Not sure,2015-07-27,23:25:00
292360,Male,South Africa,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes,2015-08-17,09:38:00
292361,Male,United States,Business,No,Yes,No,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,No,2015-08-25,19:59:00
292362,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes,2015-09-26,01:07:00
292363,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes,2016-02-01,23:04:00

**Convert the updated df into csv**

In [11]:
df_copy.to_csv('Timestamp_1')